version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling